services:
  - type: web
    name: python-openhab-rest-client-test-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --bind 0.0.0.0:$PORT --timeout 120 --worker-class gthread --threads 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
